version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: myproject-nginx
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot:/var/www/certbot
      - ./data/letsencrypt:/etc/letsencrypt   # mount cert nginx ใช้งาน
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    image: certbot/certbot
    container_name: myproject-certbot
    volumes:
      - ./data/certbot:/var/www/certbot
      - ./data/letsencrypt:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM; sleep infinity"